/*
 * SwingTableForm.java
 *
 * Created on 21 de junio de 2008, 12:01
 */

package com.swing.core.table;

/**
 *
 * @author  fernando
 */
public class SwingTableForm extends javax.swing.JPanel {

    /** Creates new form SwingTableForm */
    public SwingTableForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        xpnlCentral = new org.jdesktop.swingx.JXPanel();
        xScrollPane = new javax.swing.JScrollPane();
        xTable = new org.jdesktop.swingx.JXTable();

        btnAgregar.setText("Agregar"); // NOI18N

        btnEditar.setText("Editar"); // NOI18N
        btnEditar.setEnabled(false);

        btnQuitar.setText("Quitar"); // NOI18N
        btnQuitar.setEnabled(false);

        xpnlCentral.setLayout(new java.awt.BorderLayout());

        xTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        xScrollPane.setViewportView(xTable);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/swing/core/table/Bundle"); // NOI18N
        if (xTable.getColumnModel().getColumnCount() > 0) {
            xTable.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("SwingTableForm.xTable.columnModel.title0")); // NOI18N
            xTable.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("SwingTableForm.xTable.columnModel.title1")); // NOI18N
            xTable.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("SwingTableForm.xTable.columnModel.title2")); // NOI18N
            xTable.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("SwingTableForm.xTable.columnModel.title3")); // NOI18N
        }

        xpnlCentral.add(xScrollPane, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitar))
                    .addComponent(xpnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAgregar, btnEditar, btnQuitar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xpnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitar)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAgregar, btnEditar, btnQuitar});

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnQuitar;
    public javax.swing.JScrollPane xScrollPane;
    public org.jdesktop.swingx.JXTable xTable;
    public org.jdesktop.swingx.JXPanel xpnlCentral;
    // End of variables declaration//GEN-END:variables

}
